services:

  chat-app:
    build: .
    container_name: chat_app
    ports:
      - "3000-3010:3000-3010"
    depends_on:
      - redis
      - mongodb
      - minio
      - vaultbox_auth
    volumes:
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
    networks:
      - app_network

  vaultbox_auth:
    build:
      context: ../auth
      dockerfile: Dockerfile
    container_name: vaultbox-auth
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ../auth/src:/usr/src/app/src
      - ../auth/.env:/usr/src/app/.env
    networks:
      - app_network
    dns:
      - 8.8.8.8  # Google's DNS
    extra_hosts:
      - "smtp.gmail.com:64.233.170.109"

  minio:
    image: minio/minio:RELEASE.2023-10-25T06-33-25Z 
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    volumes:
      - minio_bucket:/data
      - ./minio-ssl:/root/.minio/certs
    command: server /data --console-address ":9001"
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app_network

  mongodb:
    image: mongo:4-focal
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

volumes:
  redis-data:
    driver: local
  minio_bucket:
    driver: local
  mongodb_data:
    driver: local

networks:
  app_network:
    driver: bridge
    external: true
